# Generated by Django 5.2.7 on 2025-10-15 11:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(max_length=500)),
                ('content_type', models.CharField(choices=[('youtube', 'YouTube Video'), ('article', 'Web Article'), ('document', 'Document'), ('other', 'Other')], max_length=20)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded Content',
                'verbose_name_plural': 'Uploaded Contents',
                'ordering': ['-created_at'],
            },
        ),
    ]
