# Generated by Django 4.2.7 on 2025-10-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={},
        ),
        migrations.RemoveField(
            model_name='summary',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='user',
        ),
        migrations.AddField(
            model_name='summary',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
