# Generated by Django 4.2.7 on 2025-10-24 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source1_type', models.CharField(choices=[('url', 'URL'), ('text', 'Text'), ('file', 'File')], max_length=10)),
                ('source1_content', models.TextField()),
                ('source2_type', models.CharField(choices=[('url', 'URL'), ('text', 'Text'), ('file', 'File')], max_length=10)),
                ('source2_content', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('similarities', models.TextField(blank=True, null=True)),
                ('differences', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
